/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.be.datafusion;

import com.carrotsearch.randomizedtesting.annotations.ThreadLeakScope;

import org.apache.arrow.c.ArrowArray;
import org.apache.arrow.c.ArrowSchema;
import org.apache.arrow.c.CDataDictionaryProvider;
import org.apache.arrow.c.Data;
import org.apache.arrow.memory.RootAllocator;
import org.apache.arrow.vector.BigIntVector;
import org.apache.arrow.vector.VectorSchemaRoot;
import org.apache.arrow.vector.types.pojo.ArrowType;
import org.apache.arrow.vector.types.pojo.Field;
import org.apache.arrow.vector.types.pojo.FieldType;
import org.apache.arrow.vector.types.pojo.Schema;
import org.apache.calcite.jdbc.JavaTypeFactoryImpl;
import org.apache.calcite.plan.RelOptCluster;
import org.apache.calcite.plan.hep.HepPlanner;
import org.apache.calcite.plan.hep.HepProgramBuilder;
import org.apache.calcite.rel.RelNode;
import org.apache.calcite.rel.core.AggregateCall;
import org.apache.calcite.rel.logical.LogicalAggregate;
import org.apache.calcite.rel.type.RelDataType;
import org.apache.calcite.rel.type.RelDataTypeFactory;
import org.apache.calcite.rex.RexBuilder;
import org.apache.calcite.sql.fun.SqlStdOperatorTable;
import org.apache.calcite.sql.type.SqlTypeName;
import org.apache.calcite.util.ImmutableBitSet;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.NumericDocValuesField;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.index.LeafReader;
import org.apache.lucene.index.NumericDocValues;
import org.apache.lucene.store.MMapDirectory;
import org.apache.lucene.tests.util.TestUtil;
import org.opensearch.action.support.PlainActionFuture;
import org.opensearch.analytics.spi.ExchangeSink;
import org.opensearch.analytics.spi.ExchangeSinkContext;
import org.opensearch.be.datafusion.nativelib.NativeBridge;
import org.opensearch.be.datafusion.nativelib.ReaderHandle;
import org.opensearch.be.datafusion.nativelib.StreamHandle;
import org.opensearch.core.action.ActionListener;
import org.opensearch.index.engine.exec.MonoFileWriterSet;
import org.opensearch.plugins.NativeStoreHandle;
import org.opensearch.test.OpenSearchTestCase;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Consumer;
import java.util.stream.Stream;

import io.substrait.extension.DefaultExtensionCatalog;
import io.substrait.extension.SimpleExtension;

import static org.apache.arrow.c.Data.importField;

/**
 * Head-to-head POC: same data, same DataFusion engine, same aggregation — storage format is
 * the only variable.
 *
 * <ul>
 *   <li><b>Path P (mustang-style):</b> parquet file on disk → DataFusion native parquet scan
 *       (ReaderHandle + executeQueryAsync, the production shard path) → GROUP BY.</li>
 *   <li><b>Path D (ours):</b> Lucene doc_values → {@link NumericDocValues#longValuesInto}
 *       bulk-decodes each column straight into Arrow vector buffers (no heap {@code long[]}
 *       in the value path) → partition-stream feed into a DataFusion LocalSession
 *       ({@link DatafusionReduceSink}) → same GROUP BY.</li>
 * </ul>
 *
 * <p>The 20M-row dataset is generated by a fixed LCG replicated bit-for-bit by
 * {@code /tmp/pvd-bench/gen_parquet.py} (which produced the parquet fixture); generator
 * checksums are asserted so the two stores can never drift. Rows 0/1 are pinned to 0/1 in
 * every column, forcing the doc-values encoder onto the {@code minValue==0/gcd==1} branch
 * that the MemorySegment decode overrides; the test asserts the direct decode actually
 * engaged (a scalar-vectorization fallback fails the run rather than silently measuring
 * the wrong path).
 */
@ThreadLeakScope(ThreadLeakScope.Scope.NONE)
public class DatafusionParquetVsDocValuesBenchTests extends OpenSearchTestCase {

    private static final int ROWS = 20_000_000;
    // 64K-row batches: the decode is random-access over a contiguous run, so batch size is
    // free to choose; larger batches amortize the per-batch C-Data export/import + channel
    // hop, which dominates path D at 4096 (measured: Q1 D=303ms at 4096-row batches).
    private static final int BATCH = 65536;
    private static final int WARMUP = 2;
    private static final int MEASURED = 5;

    private static final Path PARQUET_DIR = Path.of("/tmp/pvd-bench");
    private static final String PARQUET_FILE = "data.parquet";

    private static final long LCG_MUL = 6364136223846793005L;
    private static final long LCG_INC = 1442695040888963407L;
    private static final int KEY_LOW_CARD = 100;
    private static final int KEY_HIGH_CARD = 2_097_152;
    private static final int METRIC_CARD = 65_536;

    // From gen_parquet.py output — guards generator drift between the two stores.
    private static final long KEY_LOW_SUM = 990_001_029L;
    private static final long KEY_HIGH_SUM = 20_971_506_285_803L;
    private static final long METRIC_SUM = 655_349_845_155L;

    private static long lcg(long i) {
        return i * LCG_MUL + LCG_INC;
    }

    private static long keyLow(int i) {
        return i < 2 ? i : (lcg(i) >>> 33) % KEY_LOW_CARD;
    }

    private static long keyHigh(int i) {
        return i < 2 ? i : (lcg(i) >>> 20) % KEY_HIGH_CARD;
    }

    private static long metric(int i) {
        return i < 2 ? i : (lcg(i) >>> 10) % METRIC_CARD;
    }

    /** One benchmark query: same logical aggregation issued to both storage paths. */
    private record QuerySpec(String name, String sql, String[] dvColumns, boolean sum, int groupCard) {
    }

    private static final QuerySpec Q1 = new QuerySpec(
        "Q1 cnt(key_low)",
        "SELECT key_low, COUNT(*) AS cnt FROM test_table GROUP BY key_low",
        new String[] { "key_low" },
        false,
        KEY_LOW_CARD
    );
    private static final QuerySpec Q2 = new QuerySpec(
        "Q2 cnt(key_high)",
        "SELECT key_high, COUNT(*) AS cnt FROM test_table GROUP BY key_high",
        new String[] { "key_high" },
        false,
        KEY_HIGH_CARD
    );
    private static final QuerySpec Q3 = new QuerySpec(
        "Q3 sum(metric) by key_low",
        "SELECT key_low, SUM(metric) AS total FROM test_table GROUP BY key_low",
        new String[] { "key_low", "metric" },
        true,
        KEY_LOW_CARD
    );

    public void testParquetVsDocValues() throws Exception {
        assumeTrue(
            "parquet fixture present (generate with /tmp/pvd-bench/gen_parquet.py)",
            Files.exists(PARQUET_DIR.resolve(PARQUET_FILE))
        );

        // ---- References (arrays, computed on the fly — no 480MB row buffer) ----
        long[] refCntLow = new long[KEY_LOW_CARD];
        long[] refCntHigh = new long[KEY_HIGH_CARD];
        long[] refSumLow = new long[KEY_LOW_CARD];
        long sumLow = 0, sumHigh = 0, sumMetric = 0;
        for (int i = 0; i < ROWS; i++) {
            long kl = keyLow(i), kh = keyHigh(i), m = metric(i);
            refCntLow[(int) kl]++;
            refCntHigh[(int) kh]++;
            refSumLow[(int) kl] += m;
            sumLow += kl;
            sumHigh += kh;
            sumMetric += m;
        }
        assertEquals("generator drift: key_low checksum", KEY_LOW_SUM, sumLow);
        assertEquals("generator drift: key_high checksum", KEY_HIGH_SUM, sumHigh);
        assertEquals("generator drift: metric checksum", METRIC_SUM, sumMetric);

        // ---- Lucene index: 3 numeric doc_values columns, one merged segment, mmap ----
        Path indexDir = createTempDir("pvd-lucene");
        long tIndex = System.nanoTime();
        try (MMapDirectory dir = new MMapDirectory(indexDir)) {
            IndexWriterConfig iwc = new IndexWriterConfig().setCodec(TestUtil.getDefaultCodec()).setRAMBufferSizeMB(512);
            try (IndexWriter writer = new IndexWriter(dir, iwc)) {
                Document doc = new Document();
                NumericDocValuesField fLow = new NumericDocValuesField("key_low", 0);
                NumericDocValuesField fHigh = new NumericDocValuesField("key_high", 0);
                NumericDocValuesField fMetric = new NumericDocValuesField("metric", 0);
                doc.add(fLow);
                doc.add(fHigh);
                doc.add(fMetric);
                for (int i = 0; i < ROWS; i++) {
                    fLow.setLongValue(keyLow(i));
                    fHigh.setLongValue(keyHigh(i));
                    fMetric.setLongValue(metric(i));
                    writer.addDocument(doc);
                }
                writer.forceMerge(1);
            }
        }
        System.out.printf(
            Locale.ROOT,
            "[setup] indexed %d docs in %ds%n",
            ROWS,
            TimeUnit.NANOSECONDS.toSeconds(System.nanoTime() - tIndex)
        );
        long parquetBytes = Files.size(PARQUET_DIR.resolve(PARQUET_FILE));
        long indexBytes;
        try (Stream<Path> files = Files.list(indexDir)) {
            indexBytes = files.mapToLong(p -> p.toFile().length()).sum();
        }

        // ---- Native runtime ----
        NativeBridge.initTokioRuntimeManager(2);
        Path spillDir = createTempDir("pvd-spill");
        long runtimePtr = NativeBridge.createGlobalRuntime(2048L * 1024 * 1024, 0L, spillDir.toString(), 512L * 1024 * 1024);
        assertTrue("runtime ptr non-zero", runtimePtr != 0);
        NativeRuntimeHandle runtimeHandle = new NativeRuntimeHandle(runtimePtr);

        long tieredStorePtr = NativeStoreTestHelper.createTieredObjectStore(0L, 0L);
        NativeStoreHandle storeHandle = new NativeStoreHandle(
            NativeStoreTestHelper.getObjectStoreBoxPtr(tieredStorePtr),
            NativeStoreTestHelper::destroyObjectStoreBoxPtr
        );
        ReaderHandle readerHandle = new ReaderHandle(
            PARQUET_DIR.toString(),
            List.of(MonoFileWriterSet.of(".", 0L, PARQUET_FILE, ROWS)),
            storeHandle,
            List.of(),
            List.of()
        );

        StringBuilder table = new StringBuilder();
        table.append(
            String.format(
                Locale.ROOT,
                "%n=== parquet vs doc_values, same DataFusion engine: %d rows, %d warmup + %d measured, median ms ===%n",
                ROWS,
                WARMUP,
                MEASURED
            )
        );
        table.append(
            String.format(Locale.ROOT, "storage on disk: parquet(snappy)=%dMB lucene-index=%dMB%n", parquetBytes >> 20, indexBytes >> 20)
        );
        table.append(String.format(Locale.ROOT, "%-26s %10s %10s %14s %14s%n", "query", "P@1", "P@4", "D(dv->arrow)", "D decode-only"));

        try (
            RootAllocator alloc = new RootAllocator(Long.MAX_VALUE);
            Arena configArena = Arena.ofConfined();
            MMapDirectory dir = new MMapDirectory(indexDir);
            DirectoryReader reader = DirectoryReader.open(dir)
        ) {
            assertEquals("one merged segment", 1, reader.leaves().size());
            LeafReader leaf = reader.leaves().get(0).reader();
            assertNull("no deletes", leaf.getLiveDocs());
            assertEquals(ROWS, leaf.maxDoc());

            MemorySegment config1 = configArena.allocate(WireConfigSnapshot.BYTE_SIZE);
            WireConfigSnapshot.builder().targetPartitions(1).build().writeTo(config1);
            MemorySegment config4 = configArena.allocate(WireConfigSnapshot.BYTE_SIZE);
            WireConfigSnapshot.builder().targetPartitions(4).build().writeTo(config4);

            for (QuerySpec q : List.of(Q1, Q2, Q3)) {
                long[] refCnt = q == Q2 ? refCntHigh : (q.sum() ? refSumLow : refCntLow);
                long expectedGroups = Arrays.stream(q == Q2 ? refCntHigh : refCntLow).filter(c -> c > 0).count();
                long expectedTotal = Arrays.stream(refCnt).sum();

                // Correctness once per query per path, then timed iterations.
                verifyParquet(readerHandle, runtimeHandle, alloc, q, config4.address(), refCnt);
                verifyDocValues(reader, runtimeHandle, alloc, q, refCnt);

                long[] p1 = new long[MEASURED];
                long[] p4 = new long[MEASURED];
                long[] d = new long[MEASURED];
                long[] dDecode = new long[MEASURED];
                for (int iter = 0; iter < WARMUP + MEASURED; iter++) {
                    long tP1 = timeParquet(readerHandle, runtimeHandle, alloc, q, config1.address(), expectedGroups, expectedTotal);
                    long tP4 = timeParquet(readerHandle, runtimeHandle, alloc, q, config4.address(), expectedGroups, expectedTotal);
                    long tD = timeDocValues(reader, runtimeHandle, alloc, q, expectedGroups, expectedTotal);
                    long tDec = timeDecodeOnly(reader, alloc, q);
                    if (iter >= WARMUP) {
                        p1[iter - WARMUP] = tP1;
                        p4[iter - WARMUP] = tP4;
                        d[iter - WARMUP] = tD;
                        dDecode[iter - WARMUP] = tDec;
                    }
                    System.out.printf(
                        Locale.ROOT,
                        "[%s iter %d%s] P@1=%dms P@4=%dms D=%dms decode-only=%dms%n",
                        q.name(),
                        iter,
                        iter < WARMUP ? " warmup" : "",
                        TimeUnit.NANOSECONDS.toMillis(tP1),
                        TimeUnit.NANOSECONDS.toMillis(tP4),
                        TimeUnit.NANOSECONDS.toMillis(tD),
                        TimeUnit.NANOSECONDS.toMillis(tDec)
                    );
                }
                table.append(
                    String.format(
                        Locale.ROOT,
                        "%-26s %10d %10d %14d %14d%n",
                        q.name(),
                        TimeUnit.NANOSECONDS.toMillis(median(p1)),
                        TimeUnit.NANOSECONDS.toMillis(median(p4)),
                        TimeUnit.NANOSECONDS.toMillis(median(d)),
                        TimeUnit.NANOSECONDS.toMillis(median(dDecode))
                    )
                );
            }
            table.append(
                String.format(
                    Locale.ROOT,
                    "direct-decode engagement: %d batches direct, %d fallback (must be overwhelmingly direct)%n",
                    directBatches,
                    fallbackBatches
                )
            );
            System.out.print(table);
            assertTrue("MemorySegment decode must engage (C2 on, mmap, gcd==1 encoding)", directBatches > 0);
            assertTrue("fallback should be rare on this fixture", fallbackBatches < directBatches / 100 + 10);
        } finally {
            readerHandle.close();
            storeHandle.close();
            NativeStoreTestHelper.destroyTieredObjectStore(tieredStorePtr);
            runtimeHandle.close();
        }
    }

    // ---------------------------------------------------------------
    // Path P: parquet scan via the production executeQueryAsync route
    // ---------------------------------------------------------------

    private void verifyParquet(
        ReaderHandle readerHandle,
        NativeRuntimeHandle runtimeHandle,
        RootAllocator alloc,
        QuerySpec q,
        long configPtr,
        long[] refCnt
    ) {
        long[] got = new long[refCnt.length];
        drainParquet(readerHandle, runtimeHandle, alloc, q, configPtr, (root) -> {
            BigIntVector keys = (BigIntVector) root.getVector(0);
            BigIntVector vals = (BigIntVector) root.getVector(1);
            for (int i = 0; i < root.getRowCount(); i++) {
                got[(int) keys.get(i)] += vals.get(i);
            }
        });
        assertArrayEquals("parquet result mismatch for " + q.name(), refCnt, got);
        System.out.printf(Locale.ROOT, "[correctness] %s parquet == reference%n", q.name());
    }

    private long timeParquet(
        ReaderHandle readerHandle,
        NativeRuntimeHandle runtimeHandle,
        RootAllocator alloc,
        QuerySpec q,
        long configPtr,
        long expectedGroups,
        long expectedTotal
    ) {
        long[] acc = new long[2];
        long t0 = System.nanoTime();
        drainParquet(readerHandle, runtimeHandle, alloc, q, configPtr, (root) -> {
            int n = root.getRowCount();
            var buf = ((BigIntVector) root.getVector(1)).getDataBuffer();
            for (int i = 0; i < n; i++) {
                acc[1] += buf.getLong((long) i * Long.BYTES);
            }
            acc[0] += n;
        });
        long elapsed = System.nanoTime() - t0;
        assertEquals("parquet group count " + q.name(), expectedGroups, acc[0]);
        assertEquals("parquet total " + q.name(), expectedTotal, acc[1]);
        return elapsed;
    }

    private void drainParquet(
        ReaderHandle readerHandle,
        NativeRuntimeHandle runtimeHandle,
        RootAllocator alloc,
        QuerySpec q,
        long configPtr,
        Consumer<VectorSchemaRoot> perBatch
    ) {
        byte[] substrait = NativeBridge.sqlToSubstrait(readerHandle.getPointer(), "test_table", q.sql(), runtimeHandle.get());
        long streamPtr = asyncCall(
            listener -> NativeBridge.executeQueryAsync(
                readerHandle.getPointer(),
                "test_table",
                substrait,
                runtimeHandle.get(),
                0L,
                configPtr,
                listener
            )
        );
        try (
            StreamHandle stream = new StreamHandle(streamPtr, runtimeHandle);
            CDataDictionaryProvider dict = new CDataDictionaryProvider()
        ) {
            long schemaAddr = asyncCall(listener -> NativeBridge.streamGetSchema(stream.getPointer(), listener));
            Schema schema = new Schema(importField(alloc, ArrowSchema.wrap(schemaAddr), dict).getChildren(), null);
            try (VectorSchemaRoot root = VectorSchemaRoot.create(schema, alloc)) {
                while (true) {
                    long arrayAddr = asyncCall(listener -> NativeBridge.streamNext(runtimeHandle.get(), stream.getPointer(), listener));
                    if (arrayAddr == 0) {
                        break;
                    }
                    Data.importIntoVectorSchemaRoot(alloc, ArrowArray.wrap(arrayAddr), root, dict);
                    perBatch.accept(root);
                }
            }
        }
    }

    // ---------------------------------------------------------------
    // Path D: doc_values → longValuesInto → Arrow → DataFusion partition stream
    // ---------------------------------------------------------------

    private long directBatches = 0;
    private long fallbackBatches = 0;
    private final long[] fallbackScratch = new long[BATCH];

    private void verifyDocValues(DirectoryReader reader, NativeRuntimeHandle runtimeHandle, RootAllocator alloc, QuerySpec q, long[] refCnt)
        throws Exception {
        long[] got = new long[refCnt.length];
        runDocValues(reader, runtimeHandle, alloc, q, (root) -> {
            BigIntVector keys = (BigIntVector) root.getVector(0);
            BigIntVector vals = (BigIntVector) root.getVector(1);
            for (int i = 0; i < root.getRowCount(); i++) {
                got[(int) keys.get(i)] += vals.get(i);
            }
        });
        assertArrayEquals("doc_values result mismatch for " + q.name(), refCnt, got);
        System.out.printf(Locale.ROOT, "[correctness] %s doc_values == reference == parquet%n", q.name());
    }

    private long timeDocValues(
        DirectoryReader reader,
        NativeRuntimeHandle runtimeHandle,
        RootAllocator alloc,
        QuerySpec q,
        long expectedGroups,
        long expectedTotal
    ) throws Exception {
        long[] acc = new long[2];
        long t0 = System.nanoTime();
        runDocValues(reader, runtimeHandle, alloc, q, (root) -> {
            int n = root.getRowCount();
            var buf = ((BigIntVector) root.getVector(1)).getDataBuffer();
            for (int i = 0; i < n; i++) {
                acc[1] += buf.getLong((long) i * Long.BYTES);
            }
            acc[0] += n;
        });
        long elapsed = System.nanoTime() - t0;
        assertEquals("doc_values group count " + q.name(), expectedGroups, acc[0]);
        assertEquals("doc_values total " + q.name(), expectedTotal, acc[1]);
        return elapsed;
    }

    /**
     * Full path D run: decode the query's columns per 4096-doc batch straight into Arrow
     * vectors and feed them into a {@link DatafusionReduceSink} (LocalSession partition
     * stream) executing the equivalent GROUP BY; drain into {@code perBatch}.
     */
    private void runDocValues(
        DirectoryReader reader,
        NativeRuntimeHandle runtimeHandle,
        RootAllocator alloc,
        QuerySpec q,
        Consumer<VectorSchemaRoot> perBatch
    ) throws Exception {
        ConsumingSink downstream = new ConsumingSink(perBatch);
        ExchangeSinkContext ctx = new ExchangeSinkContext(
            "pvd-" + q.name() + "-" + System.nanoTime(),
            0,
            0L,
            buildAggSubstrait(q),
            alloc,
            List.of(new ExchangeSinkContext.ChildInput(0, buildPassthroughSubstrait(q))),
            downstream
        );
        DatafusionReduceSink sink = new DatafusionReduceSink(ctx, runtimeHandle);
        try {
            PlainActionFuture<Void> done = PlainActionFuture.newFuture();
            AtomicReference<Throwable> drainFailure = new AtomicReference<>();
            Thread drainer = new Thread(() -> {
                try {
                    sink.reduce(done);
                } catch (Throwable t) {
                    drainFailure.set(t);
                }
            }, "pvd-drainer");
            drainer.start();

            ExchangeSink child = sink.sinkForChild(0);
            LeafReader leaf = reader.leaves().get(0).reader();
            int cols = q.dvColumns().length;
            NumericDocValues[] dvs = new NumericDocValues[cols];
            for (int c = 0; c < cols; c++) {
                dvs[c] = leaf.getNumericDocValues(q.dvColumns()[c]);
                assertNotNull(q.dvColumns()[c], dvs[c]);
            }
            Schema schema = batchSchema(q);
            int[] docs = new int[BATCH];
            int maxDoc = leaf.maxDoc();
            for (int start = 0; start < maxDoc; start += BATCH) {
                int len = Math.min(BATCH, maxDoc - start);
                for (int i = 0; i < len; i++) {
                    docs[i] = start + i;
                }
                VectorSchemaRoot root = VectorSchemaRoot.create(schema, alloc);
                for (int c = 0; c < cols; c++) {
                    BigIntVector vec = (BigIntVector) root.getVector(c);
                    vec.allocateNew(len);
                    long byteLen = (long) len * Long.BYTES;
                    MemorySegment dst = MemorySegment.ofAddress(vec.getDataBuffer().memoryAddress()).reinterpret(byteLen);
                    if (dvs[c].longValuesInto(len, docs, 0, dst, 0L, 0L)) {
                        directBatches++;
                    } else {
                        // Correctness fallback: heap decode + bulk copy (still no per-value set loop).
                        fallbackBatches++;
                        dvs[c].longValues(len, docs, 0, fallbackScratch, 0, 0L);
                        dst.copyFrom(MemorySegment.ofArray(fallbackScratch).asSlice(0, byteLen));
                    }
                    vec.getValidityBuffer().setOne(0, (len + 7) / 8);
                    vec.setValueCount(len);
                }
                root.setRowCount(len);
                child.feed(root);
            }
            child.close();
            done.actionGet(300, TimeUnit.SECONDS);
            drainer.join(TimeUnit.SECONDS.toMillis(30));
            if (drainFailure.get() != null) {
                throw new IllegalStateException("drain failed", drainFailure.get());
            }
        } finally {
            sink.close();
        }
    }

    /** Decode-only cost: same batch loop, no DataFusion — isolates the doc_values→Arrow stage. */
    private long timeDecodeOnly(DirectoryReader reader, RootAllocator alloc, QuerySpec q) throws Exception {
        LeafReader leaf = reader.leaves().get(0).reader();
        int cols = q.dvColumns().length;
        NumericDocValues[] dvs = new NumericDocValues[cols];
        for (int c = 0; c < cols; c++) {
            dvs[c] = leaf.getNumericDocValues(q.dvColumns()[c]);
        }
        int[] docs = new int[BATCH];
        int maxDoc = leaf.maxDoc();
        long t0 = System.nanoTime();
        long blackhole = 0;
        try (VectorSchemaRoot root = VectorSchemaRoot.create(batchSchema(q), alloc)) {
            for (int c = 0; c < cols; c++) {
                ((BigIntVector) root.getVector(c)).allocateNew(BATCH);
            }
            for (int start = 0; start < maxDoc; start += BATCH) {
                int len = Math.min(BATCH, maxDoc - start);
                for (int i = 0; i < len; i++) {
                    docs[i] = start + i;
                }
                for (int c = 0; c < cols; c++) {
                    BigIntVector vec = (BigIntVector) root.getVector(c);
                    long byteLen = (long) len * Long.BYTES;
                    MemorySegment dst = MemorySegment.ofAddress(vec.getDataBuffer().memoryAddress()).reinterpret(byteLen);
                    if (dvs[c].longValuesInto(len, docs, 0, dst, 0L, 0L) == false) {
                        dvs[c].longValues(len, docs, 0, fallbackScratch, 0, 0L);
                        dst.copyFrom(MemorySegment.ofArray(fallbackScratch).asSlice(0, byteLen));
                    }
                    blackhole += dst.get(java.lang.foreign.ValueLayout.JAVA_LONG, 0);
                }
            }
        }
        long elapsed = System.nanoTime() - t0;
        assertTrue(blackhole != Long.MIN_VALUE);
        return elapsed;
    }

    // ---------------------------------------------------------------
    // Substrait builders for path D (Calcite → substrait, reading input-0)
    // ---------------------------------------------------------------

    private static Schema batchSchema(QuerySpec q) {
        List<Field> fields = new ArrayList<>();
        for (String col : q.dvColumns()) {
            fields.add(new Field(col, FieldType.nullable(new ArrowType.Int(64, true)), null));
        }
        return new Schema(fields);
    }

    private static RelDataType rowType(QuerySpec q, RelDataTypeFactory tf) {
        RelDataType bigint = tf.createTypeWithNullability(tf.createSqlType(SqlTypeName.BIGINT), true);
        RelDataTypeFactory.Builder b = tf.builder();
        for (String col : q.dvColumns()) {
            b.add(col, bigint);
        }
        return b.build();
    }

    private static byte[] buildAggSubstrait(QuerySpec q) {
        RelDataTypeFactory typeFactory = new JavaTypeFactoryImpl();
        RelOptCluster cluster = newCluster(typeFactory);
        RelNode scan = new DataFusionFragmentConvertor.StageInputTableScan(
            cluster,
            cluster.traitSet(),
            DatafusionMemtableReduceSink.INPUT_ID,
            rowType(q, typeFactory)
        );
        AggregateCall call = q.sum()
            ? AggregateCall.create(
                SqlStdOperatorTable.SUM,
                false,
                List.of(1),
                -1,
                typeFactory.createTypeWithNullability(typeFactory.createSqlType(SqlTypeName.BIGINT), true),
                "total"
            )
            : AggregateCall.create(SqlStdOperatorTable.COUNT, false, List.of(), -1, typeFactory.createSqlType(SqlTypeName.BIGINT), "cnt");
        LogicalAggregate agg = LogicalAggregate.create(scan, List.of(), ImmutableBitSet.of(0), null, List.of(call));
        return new DataFusionFragmentConvertor(loadExtensions()).convertFragment(agg);
    }

    private static byte[] buildPassthroughSubstrait(QuerySpec q) {
        RelDataTypeFactory typeFactory = new JavaTypeFactoryImpl();
        RelOptCluster cluster = newCluster(typeFactory);
        RelNode scan = new DataFusionFragmentConvertor.StageInputTableScan(
            cluster,
            cluster.traitSet(),
            DatafusionMemtableReduceSink.INPUT_ID,
            rowType(q, typeFactory)
        );
        return new DataFusionFragmentConvertor(loadExtensions()).convertFragment(scan);
    }

    private static RelOptCluster newCluster(RelDataTypeFactory typeFactory) {
        RexBuilder rexBuilder = new RexBuilder(typeFactory);
        HepPlanner hepPlanner = new HepPlanner(new HepProgramBuilder().build());
        return RelOptCluster.create(hepPlanner, rexBuilder);
    }

    private static SimpleExtension.ExtensionCollection loadExtensions() {
        Thread t = Thread.currentThread();
        ClassLoader prev = t.getContextClassLoader();
        try {
            t.setContextClassLoader(DatafusionParquetVsDocValuesBenchTests.class.getClassLoader());
            return DefaultExtensionCatalog.DEFAULT_COLLECTION;
        } finally {
            t.setContextClassLoader(prev);
        }
    }

    // ---------------------------------------------------------------

    private static long median(long[] values) {
        long[] sorted = values.clone();
        Arrays.sort(sorted);
        return sorted[sorted.length / 2];
    }

    private long asyncCall(Consumer<ActionListener<Long>> call) {
        CompletableFuture<Long> future = new CompletableFuture<>();
        call.accept(new ActionListener<>() {
            @Override
            public void onResponse(Long v) {
                future.complete(v);
            }

            @Override
            public void onFailure(Exception e) {
                future.completeExceptionally(e);
            }
        });
        return future.join();
    }

    /** Applies the consumer to each drained batch, then closes it. */
    private static final class ConsumingSink implements ExchangeSink {
        private final Consumer<VectorSchemaRoot> perBatch;

        ConsumingSink(Consumer<VectorSchemaRoot> perBatch) {
            this.perBatch = perBatch;
        }

        @Override
        public synchronized void feed(VectorSchemaRoot batch) {
            try {
                perBatch.accept(batch);
            } finally {
                batch.close();
            }
        }

        @Override
        public void close() {}
    }
}
